### ISSUE TITLE
Not working in PocketCasts / wrong MIME-type

### ISSUE THREAD

**Issue by phistep** [Feuermurmel/youtube-podcast-gateway#17]
The gateway does not work with PocketCasts for iOS (and I assume won't do so for Android either). The MIME-type is set to `application/atom+xml`. The correct type [seems to be](http://www.rssboard.org/rss-mime-type-application.txt) `application/rss+xml`. When set up to use this MIME-type, the feed works in PocketCasts. I have no idea if this is still compatible with other clients.

**Comment by Feuermurmel** [comment]
I think an earlier version of the gateway produced an Atom feed instead of an RSS feed and it seems I forgot to adjust the MIME type. I'm going to merge your pull request.

I use two different clients to access the feeds and neither bothered to interpret this as an error.
