### ISSUE TITLE
Watch later list is not available any more

### ISSUE THREAD

**Issue by berezovskyi** [Feuermurmel/youtube-podcast-gateway#20]
I think because of this: https://stackoverflow.com/questions/36239503/youtube-data-api-v3-playlistitems-update-not-working-for-watch-later-playlists

When I added the videos to a new playlist, everything was fine.

**Comment by Feuermurmel** [comment]
Yeah, I ran into this problem too. Using a manually created playlist instead seems to be the only fix.
