### ISSUE TITLE
Audio Only

### ISSUE THREAD

**Issue by phistep** [Feuermurmel/youtube-podcast-gateway#9]
Judging from [lib/gateway.py line 49](https://github.com/Feuermurmel/youtube-podcast-gateway/blob/78ba6be3b427105f00ff46a1945879ddfd35396c/lib/gateway.py#L49) you already have support for creating audio only feeds. How do I subscribe to them? Is there any front end? If not I think it would be a good feature to implement. I would propose an optional GET argument `?audioonly=true`.

 I'm not that fluent in Python and struggled following the flow of your application, so I unfortunately cannot do it myself. Maybe you could offer me some help so I can prepare a pull request myself (not really sure if I'll be able to do it, though) or you could do it yourself? :)

**Comment by Feuermurmel** [comment]
Hi!

Actually, yes, that feature is already there, and you almost guessed how to trigger it! Just append `?audio=true` to the URL, like so:

`.../playlist/PLKCGCG9W_E0GKM3KPlS-u-NTR2Elad61T?audio=true`
